# Generated by Django 5.1.2 on 2024-10-17 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='faketaxi',
            name='model',
        ),
        migrations.AlterField(
            model_name='faketaxi',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='faketaxi',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='faketaxi',
            name='license_plate',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='faketaxi',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taxi.driver'),
        ),
        migrations.AddField(
            model_name='faketaxi',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taxi.vehicle'),
        ),
    ]
