# Generated by Django 5.1.2 on 2024-10-22 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_driver_vehicle_remove_faketaxi_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faketaxi',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faketaxi',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.driver'),
        ),
        migrations.AlterField(
            model_name='faketaxi',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
    ]
