# Generated by Django 5.1.2 on 2024-10-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_officer_passenger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Officer',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
