# Generated by Django 5.1.2 on 2024-11-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0005_delete_officer_delete_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='nfc_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
